version: '3.8'

services:
    graphql-faker:
        image: apisguru/graphql-faker
        ports:
            - '9002:9002'
        volumes:
            - ./api-scheme.sdl:/api-scheme.sdl
        command: /api-scheme.sdl

    react-app:
        build: .
        ports:
            - '3000:80'
        depends_on:
            - graphql-faker
